### PR TITLE
Blog App: Controllers specs

### PR DESCRIPTION
**Pull request by Santiago220991**
# Tasks done:

- Added tests for users_controller.
- Added tests for posts_controller.
- Installed rspec_rails and rails_controller_testing gems.

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Santiago220991👋,

##

Good job so far coming so far with the progress you've made! 💪💪

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Good schema and controller setup.✔️
- All tests pass and are green.✔️
- App functions as it should.✔️
 
##

However, there are some issues that you still need to work on to go to the next project but you are almost there!



##

# Required Changes ♻️

- You are required to add request tests for `users` and `posts`.

image

image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

-----

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Santiago220991** [comment]
Hi @brytebee, I'll fix the issue. Thanks :+1:

**Review by descholar-ceo — APPROVED** [review]
Hi @Santiago220991 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 This PR doesn't have any linter issue ✔️ 
👍🏽 This PR follows the correct git/github flow ✔️ 
👍🏽 This PR has a descriptive PR title and comment ✔️ 
👍🏽 All requested changes have been addressed in the latest commit ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Santiago220991** [comment]
Thanks :+1:

**Pull request merged**
